### ISSUE TITLE
Possible bug in scheduling/generic

### ISSUE THREAD

**Issue by CharJon** [CharJon/GeCO#105]
I think of scheduling/generic.py contains a bug.
```python
    assignment_costs = {}
    for i in range(number_of_facilities):
        value = seed.randint(1, 10)
        for j in range(number_of_tasks):
            assignment_costs[j, i] = value

    release_times = [0] * number_of_tasks
```
The resource requirement should be fixed for every task, not every facility. Am I seeing this correctly?

**Comment by mmghannam** [comment]
You are right! great that you caught this. I added a [pull-request](#106) to fix this.
